import { createStore } from 'vuex'
import {
  getAllUsersApp,
  getAllStoreDB,
  AdminLogin,
  getAllproductsdb,
  filterProductsForString,
  filterUsersForCountry,
  productFilterDates,
  userFilterDates,
  filterUsersForCity,
  storesFilterDates,
  adminFilterDates,
  filterShops,
  getAllSpacesDB,
  getAllAdminsDB,
  filterAdmin,
  getAllSeriesDB,
  filterSeries,
  seriesFilterDates,
  filterSpaces,
} from './actions'
import {setAllUsers,
  setAllStores,
  setAdminStateLogin,
  setAllProduts,
  setAllAdmins,
setAllAdminsFilter,
  setAllProdutsFilter,
  setAllUsersFilter,
  setAllSpaces,
setAllSpacesFilter,
  setAllStoresFilter,
  setAllSeries,
setAllSeriesFilter,
} from './mutations'
import {getAllUsers,
  getAllStores,
  getAllProducts,
  getAllProductsFilter,
  getAllUsersFilter,
  getAllStoresFilter,
  getAllAdmins,
  getAllAdminsFilter,
  getAllSeries,
  getAllSeriesFilter,
  getAllSpaces,
getAllSpacesFilter,
} from './getters'


export default createStore({
  state: {
    adminStateLogin:false,
    activeWindow:1,
    listUsers:[],
    listUsersForFilter:[],
    listAdmins:[],
    listAdminsFilter:[],
    listStores:[],
    listStoresFilter:[],
    products:[],
    productsForFilter:[],
    listSeries:[],
    listSeriesFilter:[],
    listSpaces:[],
    listSpacesFilter:[],

  },
  mutations: {
    setAllUsers,
    setAllStores,
    setAdminStateLogin,
    setAllProduts,
    setAllProdutsFilter,
    setAllAdmins,
    setAllAdminsFilter,
    setAllUsersFilter,
    setAllStoresFilter,
    setAllSeries,
setAllSeriesFilter,
setAllSpaces,
setAllSpacesFilter,
    setView(state,payload){
      state.activeWindow = payload;
    }
  },
  actions: {
    getAllUsersApp,
    filterAdmin,
    getAllStoreDB,
    AdminLogin,
    adminFilterDates,
    filterUsersForCountry,
    getAllproductsdb,
    filterProductsForString,
    filterUsersForCity,
    filterShops,
    userFilterDates,
    storesFilterDates,
    productFilterDates,
    getAllAdminsDB,
    getAllSeriesDB,
    getAllSpacesDB,
    filterSpaces,
    filterSeries,
    seriesFilterDates,
    onChangeViewWindow({commit},payload){      
      commit("setView",payload);
    }
  },
  getters:{
    getAllUsers,
    getAllStores,
    getAllProducts,
    getAllUsersFilter,
    getAllProductsFilter,
    getAllStoresFilter,
    getAllAdmins,
    getAllAdminsFilter,
    getAllSeries,
    getAllSeriesFilter,
    getAllSpaces,
getAllSpacesFilter,
    getVieWindow(state){
      return state.activeWindow;
    }
  },
  modules: {
  }
})
